// StreamDeck Mobile — Streaming App Definitions
// Mirrors the desktop StreamDeck app configurations

export const STREAMING_APPS = [
  {
    id: 'netflix',
    name: 'Netflix',
    desc: 'Movies, TV Shows & Originals.',
    url: 'https://www.netflix.com',
    searchUrl: 'https://www.netflix.com/search?q=',
    color: '#E50914',
    icon: '🎬',
    letter: 'N',
  },
  {
    id: 'hotstar',
    name: 'JioHotstar',
    desc: 'TV Shows, Movies & Live Sports.',
    url: 'https://www.hotstar.com',
    searchUrl: 'https://www.hotstar.com/in/search?q=',
    color: '#001E3C',
    icon: '⭐',
    letter: 'H',
  },
  {
    id: 'youtube',
    name: 'YouTube',
    desc: 'Videos, Live & Music.',
    url: 'https://www.youtube.com',
    searchUrl: 'https://www.youtube.com/results?search_query=',
    color: '#FF0000',
    icon: '▶️',
    letter: 'Y',
  },
  {
    id: 'prime',
    name: 'Prime Video',
    desc: 'Award-winning Movies & Originals.',
    url: 'https://www.primevideo.com',
    searchUrl: 'https://www.primevideo.com/search?phrase=',
    color: '#00A8E1',
    icon: '🎥',
    letter: 'P',
  },
  {
    id: 'sonyliv',
    name: 'SonyLIV',
    desc: 'Premium Shows, Movies & Sports.',
    url: 'https://www.sonyliv.com',
    searchUrl: 'https://www.sonyliv.com/search?searchTerm=',
    color: '#2e2e6e',
    icon: '📺',
    letter: 'S',
  },
  {
    id: 'zee5',
    name: 'Zee5',
    desc: 'Unlimited Movies & Originals.',
    url: 'https://www.zee5.com',
    searchUrl: 'https://www.zee5.com/search?q=',
    color: '#821B6F',
    icon: '🎞️',
    letter: 'Z',
  },
  {
    id: 'moviebox',
    name: 'MovieBox',
    desc: 'Free Movies & TV Shows.',
    url: 'https://moviebox.mov',
    searchUrl: null,
    color: '#E21D48',
    icon: '🎬',
    letter: 'M',
    configurable: true,
  },
  {
    id: 'fancode',
    name: 'FanCode',
    desc: 'Live Sports Scores & Streaming.',
    url: 'https://fancode.com',
    searchUrl: 'https://fancode.com/search?q=',
    color: '#FF6B35',
    icon: '⚽',
    letter: 'F',
  },
  {
    id: 'anime',
    name: 'Anime Hub',
    desc: 'The best destination for Anime.',
    url: 'https://anikai.to',
    searchUrl: 'https://anikai.to/browser?keyword=',
    color: '#FF6AC1',
    icon: '🌸',
    letter: 'A',
  },
  {
    id: 'livesports',
    name: 'Live Sports',
    desc: 'Multiple Sports Providers.',
    url: null,
    searchUrl: null,
    color: '#10B981',
    icon: '🏟️',
    letter: 'L',
    isSpecial: true,
  },
];
